"""
Django settings for stayup_furniture project.

Generated by 'django-admin startproject' using Django 5.2.4.
"""

from pathlib import Path
import os
import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent


def env(key, default=""):
    return os.environ.get(key, default)


def env_bool(key, default=False):
    value = env(key, "")
    if value == "":
        return default
    return str(value).strip().lower() in ("1", "true", "yes", "on")


def env_int(key, default=0):
    value = env(key, "")
    if value == "":
        return default
    return int(value)


SECRET_KEY = env("SECRET_KEY", "django-insecure-any-random-secret-key-here")
DEBUG = env_bool("DEBUG", False)

ALLOWED_HOSTS = [
    host.strip()
    for host in env("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if host.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in env("CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]

if DEBUG:
    CSRF_TRUSTED_ORIGINS += [
        "http://localhost:8000",
        "http://127.0.0.1:8000",
        "https://*.ngrok-free.app",
        "https://*.ngrok.io",
        "https://*.ngrok-free.dev",
    ]
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SAMESITE = None
    SESSION_COOKIE_SAMESITE = None
    CSRF_ALLOW_ALL_ORIGINS = True
else:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = "Lax"
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_ALLOW_ALL_ORIGINS = False

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", not DEBUG)


INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "store",
    "cart",
    "users",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "stayup_furniture.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "cart.context_processors.cart",
                "store.context_processors.categories",
            ],
        },
    },
]

WSGI_APPLICATION = "stayup_furniture.wsgi.application"


DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR}/db.sqlite3",
    )
}

db_url = (
    os.environ.get("DATABASE_URL")
    or os.environ.get("DATABASE_PUBLIC_URL")
    or os.environ.get("POSTGRES_URL")
)
if db_url:
    DATABASES["default"] = dj_database_url.parse(db_url)
else:
    db_host = os.environ.get("PGHOST") or os.environ.get("DB_HOST") or os.environ.get("PGHOSTNAME")
    if db_host:
        DATABASES["default"] = {
            "ENGINE": "django.db.backends.postgresql",
            "HOST": db_host,
            "NAME": os.environ.get("PGDATABASE") or os.environ.get("DB_NAME") or "railway",
            "USER": os.environ.get("PGUSER") or os.environ.get("DB_USER") or "postgres",
            "PASSWORD": os.environ.get("PGPASSWORD") or os.environ.get("DB_PASSWORD") or "",
            "PORT": os.environ.get("PGPORT") or os.environ.get("DB_PORT") or "5432",
        }


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

CLOUDINARY_URL = env("CLOUDINARY_URL", "")
if CLOUDINARY_URL:
    CLOUDINARY_STORAGE = {
        "CLOUDINARY_URL": CLOUDINARY_URL,
    }
    DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "users.User"


SESSION_COOKIE_AGE = env_int("SESSION_COOKIE_AGE", 1800)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True

STATICFILES_VERSION = "1.0.0"

PAYSTACK_PUBLIC_KEY = env("PAYSTACK_PUBLIC_KEY", "")
PAYSTACK_SECRET_KEY = env("PAYSTACK_SECRET_KEY", "")
PAYSTACK_EMAIL = env("PAYSTACK_EMAIL", "payments@stayupfurniture.com")
PAYSTACK_CALLBACK_URL = env(
    "PAYSTACK_CALLBACK_URL",
    "http://localhost:8000/cart/payment/callback/",
)

EMAIL_BACKEND = env(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
EMAIL_HOST = env("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = env_int("EMAIL_PORT", 587)
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", True)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = env(
    "DEFAULT_FROM_EMAIL",
    "Stayup Nation Furniture <noreply@stayupfurniture.com>",
)

ADMIN_URL = "admin/"

JAZZMIN_SETTINGS = {
    "site_title": "Stayup Nation Admin",
    "site_header": "Stayup Nation Seller Dashboard",
    "site_brand": "Stayup Nation",
    "welcome_sign": "Welcome to the seller dashboard",
    "search_model": "store.Product",
    "user_avatar": None,
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_models": [
        "cart.Cart",
        "cart.CartItem",
        "cart.OrderItem",
        "store.ProductImage",
        "store.ProductVideo",
    ],
    "order_with_respect_to": [
        "store",
        "cart",
        "users",
        "auth",
    ],
    "icons": {
        "store.Product": "fas fa-couch",
        "store.Category": "fas fa-layer-group",
        "store.Decoration": "fas fa-paint-roller",
        "store.Review": "fas fa-star",
        "store.NewsletterSubscription": "fas fa-envelope",
        "cart.Order": "fas fa-receipt",
        "users.User": "fas fa-user",
        "auth.Group": "fas fa-users-cog",
    },
    "topmenu_links": [
        {"name": "Visit Store", "url": "/", "new_window": True},
    ],
    "custom_css": "css/admin.css",
    "custom_js": "js/admin_multiupload.js",
}

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",
    "default_theme_mode": "light",
    "navbar": "navbar-white navbar-light",
    "sidebar": "sidebar-dark-primary",
    "accent": "accent-warning",
    "brand_colour": "navbar-dark",
    "sidebar_nav_flat_style": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_child_indent": True,
    "navbar_fixed": True,
    "sidebar_fixed": True,
    "footer_fixed": False,
    "body_small_text": False,
}

handler404 = "store.views.handler404"
handler500 = "store.views.handler500"
